'use strict';
const $ = (selector) => document.querySelector(selector);
const state = { token:'', runs:[], run:null, events:[], projection:null, mode:'live', stream:null, request:null, selectedTask:null };

function el(tag, attrs={}, children=[]){const n=document.createElement(tag);for(const [k,v] of Object.entries(attrs)){if(k==='class')n.className=v;else if(k==='text')n.textContent=String(v??'');else if(k.startsWith('data-'))n.setAttribute(k,v);else n[k]=v}for(const c of [].concat(children))n.append(c instanceof Node?c:document.createTextNode(String(c)));return n}
function clear(node){node.replaceChildren()}
function empty(node,text){clear(node);node.append(el('p',{class:'empty',text}))}
function payload(event){return event.payload||event.data||{}}
function sequence(event){return Number(event.sequence??event.id??0)}
function time(value){if(!value)return '—';const d=new Date(value);return Number.isNaN(d.valueOf())?'—':new Intl.DateTimeFormat(undefined,{hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(d)}
function date(value){if(!value)return '—';const d=new Date(value);return Number.isNaN(d.valueOf())?'—':new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(d)}
function notice(text,error=false){$('#notice').textContent=text;$('#notice').classList.toggle('error',error)}
function headers(extra={}){const h={...extra};if(state.token)h.Authorization=`Bearer ${state.token}`;return h}
async function api(path,options={}){const response=await fetch(path,{...options,headers:headers(options.headers||{})});const body=await response.json().catch(()=>({}));if(response.status===401){$('#authDialog').showModal();throw new Error('Authentication required')}if(!response.ok)throw new Error(body.error||`${response.status} ${response.statusText}`);return body}

async function boot(){try{const health=await api('/healthz');if(health.mode&&health.mode!=='dispatch')throw new Error(`Expected Dispatch backend, found ${health.mode}`);connected(true);await loadRuns();notice('Dispatch connected. Select a run to inspect persisted evidence.')}catch(error){connected(false);notice(error.message,true)}}
function connected(ok){$('#connectionDot').className=ok?'ok':'bad';$('#connectionText').textContent=ok?'Connected':'Offline'}
async function loadRuns(select){const data=await api('/api/v1/runs');state.runs=data.runs||[];renderRuns();const wanted=select||state.run?.id||state.runs.at(-1)?.id;if(wanted)await selectRun(wanted)}
function renderRuns(){const root=$('#runs');clear(root);$('#runCount').textContent=state.runs.length;if(!state.runs.length)return empty(root,'No dispatch runs yet.');for(const run of [...state.runs].reverse()){const button=el('button',{class:`run${state.run?.id===run.id?' active':''}`});button.append(el('strong',{text:run.name||run.id}),el('small',{},[el('span',{text:run.mode||'dispatch'}),el('time',{text:date(run.created_at)})]));button.addEventListener('click',()=>selectRun(run.id));root.append(button)}}
async function selectRun(id){stopStream();state.run=state.runs.find(r=>r.id===id)||{id};const [eventData,projection]=await Promise.all([api(`/api/v1/runs/${encodeURIComponent(id)}/events`),api(`/api/v1/runs/${encodeURIComponent(id)}/projection`)]);state.events=eventData.events||[];state.projection=projection;state.request=null;state.selectedTask=null;$('#replayRange').max=sequence(state.events.at(-1));$('#replayRange').value=$('#replayRange').max;$('#replayValue').value=$('#replayRange').value;renderRuns();render();if(state.mode==='live')startStream();notice(`Showing ${state.events.length} persisted events for ${state.run.name||id}.`)}
function visibleEvents(){if(state.mode==='live')return state.events;const upto=Number($('#replayRange').value);return state.events.filter(e=>sequence(e)<=upto)}
function derive(events){const tasks=new Map(),agents=new Map(),routes=[],collab=[],approvals=new Map(),deps=[];for(const event of events){const p=payload(event),type=event.type||'',seq=sequence(event);const taskId=p.task||p.task_id||event.subject?.id;if(type==='dispatch.started'){for(const id of p.agents||[])agents.set(String(id),{id:String(id),health:'observed',capabilities:[]});for(const dep of p.dependencies||[]){const [from,to]=String(dep).split('->');if(from&&to)deps.push({from,to})}}
      if(taskId&&(type.startsWith('task.')||type.startsWith('command.')||type.startsWith('control.'))){const task=tasks.get(taskId)||{id:taskId,status:'observed',attempt:'—',agent:'—',reason:'—',seq:0,fencingToken:0};if(type.startsWith('task.'))task.status=type.slice(5);task.seq=seq;task.agent=p.to||p.agent||p.agent_id||task.agent;task.attempt=p.attempt??task.attempt;task.reason=p.reason||task.reason;task.depends=p.depends_on||task.depends;task.fencingToken=Number(p.fencing_token)||task.fencingToken;tasks.set(taskId,task)}
      if(type==='task.delegated'||type==='route.decided'||type==='routing.decided'){const decision=p.decision||p,candidates=decision.candidates||[],excluded=decision.exclusions||decision.excluded||[];routes.push({seq,task:taskId||'—',selected:p.agent_id||decision.to||decision.selected||decision.agent||'—',reason:decision.reason||'Not recorded',candidates,excluded});const task=tasks.get(taskId)||{id:taskId,status:'delegated',attempt:'—',seq,fencingToken:0};task.agent=p.agent_id||decision.to||decision.selected||task.agent||'—';task.reason=decision.reason||task.reason||'—';task.fencingToken=Number(p.fencing_token)||task.fencingToken;task.status=type==='task.delegated'?'delegated':task.status;task.seq=seq;tasks.set(taskId,task)}
      if(type.startsWith('agent.')){const id=p.agent||p.agent_id||event.subject?.id||'unknown';const agent=agents.get(id)||{id,capabilities:[]};agent.health=p.health||type.slice(6);agent.capabilities=p.capabilities||agent.capabilities;agent.version=p.version||agent.version;agents.set(id,agent)}
      if(type==='message.sent'||type==='artifact.created')collab.push({type,seq,p,time:event.occurred_at});
      if(type.startsWith('approval.')){const key=p.action_digest||p.digest||taskId||String(seq);const approval=approvals.get(key)||{digest:key,task:taskId,status:'requested',seq};approval.status=type.slice(9);approval.actor=p.actor;approval.expires=p.expires;approval.seq=seq;approvals.set(key,approval)}
    }return {tasks:[...tasks.values()],agents:[...agents.values()],routes,collab,approvals:[...approvals.values()],deps}}
function render(){const events=visibleEvents(),d=derive(events),p=state.projection||{};$('#runTitle').textContent=state.run?.name||state.run?.id||'Select a run';$('#status').textContent=p.status||statusFrom(events);$('#taskMetric').textContent=d.tasks.length;$('#agentMetric').textContent=d.agents.filter(a=>!['offline','failed','disabled'].includes(a.health)).length;$('#approvalMetric').textContent=d.approvals.filter(a=>a.status==='requested').length;$('#lastMetric').textContent=sequence(events.at(-1))||'—';renderTasks(d.tasks);renderDAG(d.tasks,d.deps);renderAgents(d.agents);renderRoutes(d.routes);renderCollaboration(d.collab);renderApprovals(d.approvals);renderTimeline(events);setControls(Boolean(state.run)&&state.mode==='live')}
function statusFrom(events){const type=events.at(-1)?.type||'created';if(type.endsWith('.completed'))return 'completed';if(type.endsWith('.failed'))return 'failed';if(type.includes('cancelled'))return 'cancelled';return events.length?'running':'created'}
function renderTasks(tasks){const body=$('#tasks');clear(body);if(!tasks.length)return body.append(el('tr',{},el('td',{class:'empty',colSpan:6,text:'No task evidence in this view.'})));for(const task of tasks.sort((a,b)=>a.id.localeCompare(b.id))){const row=el('tr');row.classList.toggle('selected',state.selectedTask?.id===task.id);row.append(el('td',{text:task.id}),el('td',{},el('span',{class:`status ${task.status}`,text:task.status})),el('td',{text:task.agent||'—'}),el('td',{text:task.attempt}),el('td',{text:task.reason||'—'}),el('td',{class:'mono',text:`#${task.seq}`}));row.addEventListener('click',()=>{state.selectedTask={id:task.id,fencingToken:task.fencingToken||0,status:task.status};render();notice(task.fencingToken?`Task ${task.id} selected with fence ${task.fencingToken}.`:`Task ${task.id} has no active fence; controls remain disabled.`)});body.append(row)}}
function renderDAG(tasks,deps){const root=$('#dag');clear(root);const edges=[...deps];for(const task of tasks)for(const dep of task.depends||[])edges.push({from:dep,to:task.id});if(!edges.length){for(const task of tasks)root.append(dagNode(task));if(!tasks.length)empty(root,'No dependency evidence.');return}const ordered=[];for(const edge of edges){if(!ordered.includes(edge.from))ordered.push(edge.from);if(!ordered.includes(edge.to))ordered.push(edge.to)}ordered.forEach((id,i)=>{const task=tasks.find(t=>t.id===id)||{id,status:'dependency'};root.append(dagNode(task));if(i<ordered.length-1)root.append(el('span',{class:'edge','aria-hidden':'true',text:'→'}))})}
function dagNode(task){return el('div',{class:'dag-node'},[el('b',{text:task.id}),el('small',{text:task.status})])}
function renderAgents(agents){const root=$('#agents');clear(root);if(!agents.length)return empty(root,'No agent evidence.');for(const agent of agents){const card=el('article',{class:'agent'}),head=el('div',{class:'agent-head'},[el('strong',{text:agent.id}),el('span',{class:`status ${agent.health}`,text:agent.health||'observed'})]),chips=el('div',{class:'chips'});for(const cap of agent.capabilities||[])chips.append(el('span',{class:'chip',text:cap}));card.append(head,el('small',{text:agent.version?`Version ${agent.version}`:'Version not recorded'}),chips);root.append(card)}}
function renderRoutes(routes){const root=$('#routes');clear(root);if(!routes.length)return empty(root,'No route-decision evidence.');for(const route of routes){const card=el('article',{class:'decision'}),head=el('div',{class:'decision-head'},[el('strong',{text:`${route.task} → ${route.selected}`}),el('span',{class:'mono',text:`#${route.seq}`})]),chips=el('div',{class:'chips'});for(const c of route.candidates||[])chips.append(el('span',{class:'chip',text:`candidate: ${typeof c==='object'?JSON.stringify(c):c}`}));for(const x of route.excluded||[])chips.append(el('span',{class:'chip excluded',text:`excluded: ${typeof x==='object'?JSON.stringify(x):x}`}));card.append(head,el('p',{text:route.reason}),chips);root.append(card)}}
function renderCollaboration(items){const root=$('#collaboration');clear(root);if(!items.length)return empty(root,'No messages or artifacts.');for(const item of items){const p=item.p,title=item.type==='message.sent'?`${p.from||'—'} → ${p.to||'—'}`:p.name||'Unnamed artifact';root.append(el('article',{class:'feed-item'},[el('div',{class:'feed-head'},[el('strong',{text:title}),el('time',{text:`${time(item.time)} · #${item.seq}`})]),el('p',{text:p.summary||p.task||p.uri||p.digest||item.type})]))}}
function renderApprovals(items){const root=$('#approvals');clear(root);if(!items.length)return empty(root,'No approval evidence.');for(const item of items){const card=el('article',{class:'feed-item'}),head=el('div',{class:'feed-head'},[el('strong',{text:item.task||'Action approval'}),el('span',{class:`status ${item.status}`,text:item.status})]);card.append(head,el('p',{class:'mono',text:item.digest}),el('p',{text:[item.actor&&`Actor ${item.actor}`,item.expires&&`Expires ${item.expires}`].filter(Boolean).join(' · ')||'Awaiting backend evidence'}));if(item.status==='requested'&&state.mode==='live'){const actions=el('div',{class:'chips'});for(const decision of ['grant','deny']){const b=el('button',{class:'secondary',text:decision});b.addEventListener('click',()=>approvalAction(item,decision));actions.append(b)}card.append(actions)}root.append(card)}}
function renderTimeline(events){const body=$('#timeline');clear(body);if(!events.length)return body.append(el('tr',{},el('td',{class:'empty',colSpan:4,text:'No events in this view.'})));for(const event of events){const cells=el('div',{class:'event-data'});for(const [key,value] of Object.entries(payload(event)))cells.append(el('span',{title:String(typeof value==='object'?JSON.stringify(value):value),text:`${key}: ${typeof value==='object'?JSON.stringify(value):value}`}));const row=el('tr');row.append(el('td',{class:'mono',text:sequence(event)}),el('td',{text:time(event.occurred_at)}),el('td',{class:'event',text:event.type}),el('td',{},cells));body.append(row)}}

async function startStream(){if(!state.run||state.mode!=='live')return;const controller=new AbortController();state.stream=controller;let cursor=sequence(state.events.at(-1));try{const response=await fetch(`/api/v1/runs/${encodeURIComponent(state.run.id)}/events?after=${cursor}`,{headers:headers({Accept:'text/event-stream'}),signal:controller.signal});if(!response.ok)throw new Error(`Live stream ${response.status}`);const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const chunks=buffer.split('\n\n');buffer=chunks.pop();for(const chunk of chunks){const line=chunk.split('\n').find(x=>x.startsWith('data:'));if(!line)continue;const event=JSON.parse(line.slice(5).trim());if(sequence(event)>cursor){state.events.push(event);cursor=sequence(event);render();evaluateRequest(event)}}}}catch(error){if(error.name!=='AbortError'){connected(false);notice(error.message,true)}}}
function stopStream(){state.stream?.abort();state.stream=null}
function evaluateRequest(event){if(!state.request)return;const p=payload(event),type=event.type||'';if(!type.includes(state.request.action.replace('emergency-stop','emergency'))&&!['control.acknowledged','control.failed'].includes(type))return;if(type.endsWith('.requested'))return;const failed=type.endsWith('.failed')||p.acknowledged===false;$('#controlState').textContent=failed?`${state.request.action} failed: ${p.reason||'backend rejected request'}`:`${state.request.action} acknowledged by event #${sequence(event)}.`;$('#controlState').className=failed?'control-help request-state':'control-help';state.request=null}
async function sendControl(action){if(!state.run)return;const emergency=action==='emergency-stop',target=emergency?null:state.selectedTask?.id,fencingToken=emergency?0:state.selectedTask?.fencingToken;if(!emergency&&(!target||!fencingToken)){notice('Select a task with a current fencing token first.',true);return}state.request={action,target};$('#controlState').textContent=`${action} requested${target?` for ${target}`:''}; awaiting backend acknowledgement…`;$('#controlState').className='control-help request-state';try{await api(`/api/v1/runs/${encodeURIComponent(state.run.id)}/controls/${encodeURIComponent(action)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({task_id:target,fencing_token:fencingToken})})}catch(error){state.request=null;state.selectedTask=null;$('#controlState').textContent=`${action} request failed: ${error.message}`;notice(error.message,true)}}
async function approvalAction(item,decision){try{await api(`/api/v1/runs/${encodeURIComponent(state.run.id)}/approvals/${encodeURIComponent(item.digest)}/${decision}`,{method:'POST'});notice(`${decision} requested; awaiting a persisted approval event.`)}catch(error){notice(error.message,true)}}
function setControls(enabled){const terminal=['completed','failed','cancelled','interrupted','emergency_stopped'].includes(state.projection?.status);document.querySelectorAll('[data-control]').forEach(b=>{const emergency=b.dataset.control==='emergency-stop';b.disabled=!enabled||terminal||(!emergency&&(!state.selectedTask?.id||!state.selectedTask?.fencingToken))});$('#export').disabled=!state.run}
async function exportBundle(){if(!state.run)return;try{const response=await fetch(`/api/v1/runs/${encodeURIComponent(state.run.id)}/export`,{headers:headers()});if(!response.ok)throw new Error(`Export ${response.status}`);const blob=await response.blob(),url=URL.createObjectURL(blob),a=el('a',{href:url,download:`n0ding-dispatch-${state.run.id}.json`});a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(error){notice(error.message,true)}}

$('#refresh').addEventListener('click',()=>loadRuns().catch(e=>notice(e.message,true)));$('#startFixture').addEventListener('click',async()=>{try{const run=await api('/api/v1/fixtures',{method:'POST'});await loadRuns(run.id)}catch(error){notice(error.message,true)}});document.querySelectorAll('[data-control]').forEach(b=>b.addEventListener('click',()=>sendControl(b.dataset.control)));$('#export').addEventListener('click',exportBundle);document.querySelectorAll('.mode').forEach(button=>button.addEventListener('click',async()=>{state.mode=button.dataset.mode;document.querySelectorAll('.mode').forEach(x=>{x.classList.toggle('active',x===button);x.setAttribute('aria-pressed',String(x===button))});$('#replayControl').hidden=state.mode!=='replay';if(state.mode==='replay')stopStream();else startStream();if(state.run)state.projection=await api(`/api/v1/runs/${encodeURIComponent(state.run.id)}/projection${state.mode==='replay'?`?upto=${$('#replayRange').value}`:''}`);render()}));$('#replayRange').addEventListener('input',async event=>{$('#replayValue').value=event.target.value;if(state.run)state.projection=await api(`/api/v1/runs/${encodeURIComponent(state.run.id)}/projection?upto=${event.target.value}`);render()});$('#authButton').addEventListener('click',()=>$('#authDialog').showModal());$('#saveToken').addEventListener('click',()=>{state.token=$('#tokenInput').value;$('#tokenInput').value='';setTimeout(boot,0)});window.addEventListener('beforeunload',stopStream);boot();
